module.exports = {
	NODE_ENV: process.env.NODE_ENV,
	PORT: process.env.PORT || 8000,
	URL: process.env.NODE_ENV === "production" ? "https://hoy.im/" : "http://localhost/",
	MONGO_URL: process.env.MONGODB_URI || "mongodb://localhost:27017/hoy-dev",
	PAGE_LIMIT: process.env.PAGE_LIMIT || 50,
	SECRET: process.env.SECRET || "some-secret",
	AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
	AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
	VAPID_PUBLIC_KEY: process.env.VAPID_PUBLIC_KEY,
	VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,
	PUSH_OPTIONS: {
		vapidDetails: {
			subject: "mailto:vasanth@hoy.im",
			publicKey: process.env.VAPID_PUBLIC_KEY,
			privateKey: process.env.VAPID_PRIVATE_KEY,
		},
	},
	INVALID_HANDLES: [
		"bot",
		"login",
		"register",
		"signin",
		"signup",
		"forgot",
		"reset",
		"account",
		"profile",
		"logout",
		"admin",
		"administrator",
		"api",
		"pages",
		"home",
		"page",
		"global",
		"share",
		"nearby",
		"mentions",
		"search",
		"find",
		"app",
		"settings",
		"auth",
		"authorize",
		"404",
		"notfound",
		"webhook",
		"activate",
		"email",
		"verify",
		"verified",
		"blarb",
		"blarbco",
		"users",
		"followers",
		"followings",
		"follows",
		"terms",
		"legal",
		"privacy",
		"avatar",
		"image",
		"credits",
	],
	FEATURE_FLAGS: {
		enable_basic_auth: false,
	},
};
